# -*- coding: utf-8 -*-
"""yolo1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wq1tZmDG_tFDZ05ssKqmIZsXc2nJz99f
"""

from google.colab import drive

drive.mount('/content/gdrive')

!nvidia-smi

!ls '/content/gdrive/My Drive/yolo/data'

DATA_DIR = '/content/gdrive/My Drive/yolo/data'

!pip install ultralytics

import os

from ultralytics import YOLO


# Load a model
model = YOLO("yolov8n-cls.pt")  # load a pretained model

#Use the model
results = model.train(data=DATA_DIR, epochs=20, imgsz=64)  # train the model

!scp -r /content/runs '/content/gdrive/My Drive/yolo'

import os
import pandas as pd
import matplotlib.pyplot as plt

results_path = '/content/gdrive/My Drive/yolo/runs/classify/train2/results.csv'

results = pd.read_csv(results_path)

plt.figure()
plt.plot(results['                  epoch'], results['             train/loss'], label='train loss')
plt.plot(results['                  epoch'], results['               val/loss'], label='val loss', c='red')
plt.grid()
plt.title('Loss vs epochs')
plt.ylabel('loss')
plt.xlabel('epochs')
plt.legend()


plt.figure()
plt.plot(results['                  epoch'], results['  metrics/accuracy_top1'] * 100)
plt.grid()
plt.title('Validation accuracy vs epochs')
plt.ylabel('accuracy (%)')
plt.xlabel('epochs')

plt.show()

from ultralytics import YOLO
model = YOLO('/content/gdrive/My Drive/yolo/runs/classify/train2/weights/last.pt')  # load a custom model
import numpy as np
import cv2

results = model('/content/gdrive/MyDrive/yolo/test.jpeg')  # predict on an image

names_dict = results[0].names

probs = results[0].probs.data.tolist()

print(names_dict)
print(probs)

print(names_dict[np.argmax(probs)])
img=cv2.imread("/content/gdrive/MyDrive/yolo/test.jpeg")

